=== Stratadox/CardGame/schema/proposals/v1/overview.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://github.com/Stratadox/CardGame/tree/master/schema/proposals/v1/overview.schema.json",
  "allOf": [
    {
      "$ref": "../../hal.schema.json"
    }
  ],
  "properties": {
    "_links": {},
    "_embedded": {},
    "id": {
      "title": "The proposal identifier, uuid",
      "type": "string"
    },
    "from": {
      "title": "The player that proposed the match",
      "type": "string"
    },
    "to": {
      "title": "The player that received the proposal",
      "type": "string"
    },
    "valid-until": {
      "title": "The point in time when the proposal expires",
      "type": "string",
      "format": "date-time"
    },
    "accepted": {
      "title": "Whether the proposal has been accepted",
      "type": "boolean",
      "default": false
    }
  },
  "required": [
    "id",
    "from",
    "to",
    "valid-until"
  ],
  "additionalProperties": false
}

=== Stratadox/CardGame/schema/proposals/v1/example/overview.json
{
  "_links": {
    "self": { "href": "test://match/proposals/(PROPOSAL)/" },
    "curies": [
      {
        "name": "proposal",
        "href": "https://github.com/Stratadox/CardGame/tree/master/docs/relation/proposals/{rel}",
        "templated": true
      }
    ],
    "proposal:from": { "href": "test://account/(OTHER-ACCOUNT)/" },
    "proposal:to": { "href": "test://account/(ACCOUNT)/" },
    "proposal:accept": { "href": "test://match/proposals/(PROPOSAL)/accept/" }
  },
  "id": "(PROPOSAL)",
  "from": "(OTHER-ACCOUNT)",
  "to": "(ACCOUNT)",
  "valid-until": "(EXPIRE)"
}
